name: zartek
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.2
  connectivity_plus: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  go_router: ^9.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  sizer: ^2.0.15
  firebase_core:
  firebase_auth:
  google_sign_in:
  hydrated_bloc: ^9.1.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data.json
